### ISSUE TITLE
topics/dg-organize-framework-files.dita

### ISSUE THREAD

**Issue by tgraham-antenna** [oxygenxml/userguide#65]
1. The sample directory structure doesn't include the 'images' directory.
2. The text doesn't mention that it's also possible to specify additional framework directories.
3. "The following folder structure will be created:" implies that it's automatic, but AFAICT, the user is supposed to create the directories.
4. It also seems to me that this topics reads like it should be the first topic under "Creating the Basic Association".

**Comment by StevenHiggs** [comment]
Tony,
I also noticed that this section is confusing at times when I was reading parts of it awhile back.  As soon as I have time I will work on revising the whole section "Advanced Customization Tutorial". I remember thinking that it doesn't make sense that the "Document Type Settings" section refers to the sample "SDF" framework but that framework isn't even created until a later section of the tutorial. Anyway, my initial thoughts in regards to your suggestions are as follows:

1. I'm assuming that this wasn't included when the documentation was written because the tutorial doesn't really cover adding images to the framework since it's optional. I think it would be useful information so I will incorporate this somewhere in the section.
2. When I revise the section, it will be structured differently and this will be more clear. It needs to be more clear that the "SDF" framework is just an example that we use to show the user how to create and customize a framework, but they can use oXygen to customize their framework structure however they like (including multiple frameworks).
3. I agree and I will fix this. I will make it more instructional.
4. I agree. This should be the first step (not the "XML Schema" topic) in the "Creating the Basic Association" section. Other notes for myself: The "Schema Settings" topic should be a child of "XML Schema". The 'Styling' topics should be grouped as children of a generic styling topic. This whole section should be moved higher in the ditamap so that the instructions for creating the sample "SDF" framework is explained before it is mentioned. It would also be a good idea to make all the sections in this ditamap so that they can stand alone.

**Comment by StevenHiggs** [comment]
Alex reorganized and improved that chapter a few years ago so I think we can close this.
